Add feature module
newfold-labs/wp-module-patterns pull request #74
Opened 2024-05-24 18:38 UTC by circlecube

## Proposed changes

This integrates the features module with the patterns module. It will allow users to toggle the feature on/off in the plugin settings. The features module changes the way a module is loaded, replacing the module loader/register method with a feature class and instantiate method which kicks the module off. If it is disabled, the installation will not run. Integrating with the new feature module is a clean way to only load this module code when it is enabled, and wraps everything into a features API that can be used by the plugins (and even other modules). It also allows us to disable the feature in certain scenarios (like on bluehost cloud platform), but still allows the user to enable it.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-05-24 18:52 UTC, wpscholar requested changes

2024-05-24 18:52 UTC, wpscholar commented on includes/PatternsFeature.php
> +				}
Looks like we have some code formatting issues here that we should resolve.

2024-05-24 19:01 UTC, wpscholar commented on includes/PatternsFeature.php
> +                        define( 'NFD_WONDER_BLOCKS_BUILD_DIR', __DIR__ . '/build/' . NFD_WONDER_BLOCKS_VERSION );
```suggestion
                        define( 'NFD_WONDER_BLOCKS_BUILD_DIR', NFD_WONDER_BLOCKS_DIR . '/build/' . NFD_WONDER_BLOCKS_VERSION );
```
```suggestion
                        define( 'NFD_WONDER_BLOCKS_BUILD_DIR', __DIR__ . '/build/' . NFD_WONDER_BLOCKS_VERSION );
```

2024-05-24 19:02 UTC, wpscholar commented on includes/PatternsFeature.php
> +                    }
Move to `bootstrap.php`

2024-05-24 19:33 UTC, wpscholar commented on includes/PatternsFeature.php
> +                    new Patterns( $container );
Code formatting

2024-05-24 20:34 UTC, circlecube commented on includes/PatternsFeature.php
> +                        define( 'NFD_WONDER_BLOCKS_BUILD_DIR', __DIR__ . '/build/' . NFD_WONDER_BLOCKS_VERSION );
Thanks, moved these back to bootstrap file

2024-05-28 15:01 UTC, zlateska approved these changes

2024-05-29 15:29 UTC, merged